DECLARE
EMP_NO NUMBER;
V_EMP_NO NUMBER:=5587;
BEGIN
SELECT emp_number INTO EMP_NO FROM employee
WHERE emp_number=V_EMP_NO;
DBMS_OUTPUT.PUT_LINE('employee number is : '|| EMP_NO);
EXCEPTION 
WHEN NO_DATA_FOUND THEN
DBMS_OUTPUT.PUT_LINE(SQLERRM);
END;
/