CREATE OR REPLACE PROCEDURE sequre (x IN NUMBER) 
IS
BEGIN
z NUMBER;
z:=x*x;
DBMS_OUTPUT.PUT_LINE('sequre of ' || x || ' is : ' || z);
EXCEPTION 
WHEN OTHERS THEN
DBMS_OUTPUT.PUT_LINE(SQLERRM);
END;